# Generated by Django 5.2 on 2026-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test', 'order'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['test_result', 'question__order'], 'verbose_name': 'Savol Javob', 'verbose_name_plural': 'Savol Javoblari'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at'], 'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Test Natijasi', 'verbose_name_plural': 'Test Natijalari'},
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A variyant'), ('B', 'B variyant'), ('C', 'C variyant'), ('D', 'D variyant')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='time_spent',
            field=models.IntegerField(help_text="Bu savol uchun soniyalar bilan o'tgan vaqt"),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='user_answer',
            field=models.CharField(blank=True, choices=[('A', 'A variyant'), ('B', 'B variyant'), ('C', 'C variyant'), ('D', 'D variyant'), ('', 'Javob berilmadi')], max_length=1),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(help_text="Soniyalar bilan o'tgan vaqt"),
        ),
    ]
