# Generated by Django 5.2 on 2026-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text="Bo'sh qoldirilsa, avtomat raqamlanadi"),
        ),
    ]
