# Generated by Django 5.2 on 2026-06-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['test_result', 'id'], 'verbose_name': 'Savol Javob', 'verbose_name_plural': 'Savol Javoblari'},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
