# Generated by Django 5.2 on 2026-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_customuser_last_seen_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('ALGO', 'Algoritmik fikrlash'), ('MATH', 'Matematik bilim'), ('CREAT', 'Kreativlik'), ('SPEED', 'Muammo yechish tezligi')], default='ALGO', max_length=10),
        ),
    ]
